### ISSUE TITLE
Sugerencia: Quitar el height a los divs de los cuerpos para que no posean scroll

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-vidal#10]
![image](https://github.com/UCC-LabCompu2/proyecto2024-vidal/assets/8345007/efb49583-d47e-4800-be11-d439ffa2a370)

**Comment by mat1v1dal** [comment]
Puse el scroll con el objetivo de que cuando se quiere cambiar la posicion de los objetos, se pueda ver el movimiento en el canvas al mismo tiempo que se mueve la posicion, para asi evitar scrollear la pagina para visualizar los cambios
