### ISSUE TITLE
Sugerencia: Agregar botón para reiniciar simulación

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-vidal#13]
![imagen](https://github.com/UCC-LabCompu2/proyecto2024-vidal/assets/8345007/4b5888b3-5c8a-423b-b8b3-16ca0635483a)

**Comment by mat1v1dal** [comment]
El botón de basura hace la función de reiniciar la simulación, pero le cambiaré el icono para que se distinga mejor.
