### ISSUE TITLE
Errores presentes al realizar un inspect code

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-vidal#3]
En Webstorm Code > Inspect Code para verificar que no haya errores.

![imagen](https://github.com/UCC-LabCompu2/proyecto2024-vidal/assets/8345007/cd526ba2-6e50-48ea-b1fa-2b7d872b9a78)

**Comment by mat1v1dal** [comment]
![Screenshot_11](https://github.com/UCC-LabCompu2/proyecto2024-vidal/assets/142534091/4eb3120a-f31f-4e85-acfa-862e356522ff)
