### ISSUE TITLE
CSS: En style.css se emplea una fuente que no fue importada antes (por lo tanto, la página no se renderiza con esa fuente)

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-vidal#4]
https://github.com/UCC-LabCompu2/proyecto2024-vidal/blob/0f922f49bf53d00caa552a4e0a251c5376bf8c3c/styles.css#L11

En la página index.html solo se hace el import de styles.css. Esa hoja de estilo no incluye el import, por lo que la fuente nunca se renderiza.

**Comment by mat1v1dal** [comment]
@import url("https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap");
