### ISSUE TITLE
Emplear al menos 3 etiquetas semánticas diferentes

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-vidal#7]
Emplear al menos 3 [etiquetas semánticas](https://ucc-labcompu2.github.io/filminas/U4_HTML.html#/11) diferentes (header, nav, aside, main, section, article, footer)

**Comment by mat1v1dal** [comment]
Implementé las etiquetas semanticas en el popup, ya que al hacerlo en la página principal tenía varios errores.
